# Generated by Django 5.1.6 on 2025-11-12 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda_base', models.CharField(max_length=3)),
                ('moneda_destino', models.CharField(max_length=3)),
                ('cantidad', models.DecimalField(decimal_places=6, max_digits=30)),
                ('resultado', models.DecimalField(decimal_places=6, max_digits=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
